version: "2"
services:
  - type: web
    name: energiapp-tfb
    env: node
    plan: free
    buildCommand: |
      npm install
      cd backend && npm install && cd ..
      cd frontend && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
