version: "2"
build:
  commands:
    - npm install
    - cd backend && npm install && cd ..
    - cd frontend && npm install && npm run build && cd ..
start:
  command: NODE_ENV=production node backend/server.js
