version: "2"
services:
  - type: web
    name: energiapp-tfb
    env: node
    plan: free
    buildCommand: |
      npm install
      cd backend && npm install && cd ..
      cd frontend && npm install && npm run build && cd ..
    startCommand: node backend/server-simple.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: tu_jwt_secret_super_seguro_para_produccion_2024
      - key: FRONTEND_URL
        value: https://energiapp-tfb.onrender.com
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://energiapp-tfb.onrender.com
      - key: LOG_LEVEL
        value: info
